### ISSUE TITLE
date_ranges NA in GTOP30 metadata

### ISSUE THREAD

**Issue by HaitaoHuang-USDA** [USDA-SCINet/rgeocdl#14]
The following table was extracted from view_metadata() for each dataset.

GTOPO30, all year, month, day in date_range are empty.

```
dataset,year[1],year[2],month[1],month[2],day[1],day[2]
DaymetV4,1980,2020,1980-01,2020-12,1980-01-01,2020-12-31
GTOPO30,NA,NA,NA,NA,NA,NA
MODIS_NDVI,NA,NA,NA,NA,2000-01-01,2015-12-31
NASS_CDL,2008,2021,NA,NA,NA,NA
PRISM,1895,2020,1895-01,2021-01,1981-01-01,2021-01-31
VIP,1981,2014,1981-01,2014-12,1981-01-01,2014-12-31
```

**Comment by HeatherSavoy-USDA** [comment]
I've updated the documentation about dates - see the 'Details' section of `download_subset`. And I changed the `view_metadata` output to say '(no data for this temporal grain)' instead of NA or NULL. Please check if these changes resolved your issue.

**Comment by HaitaoHuang-USDA** [comment]
Yes. It resolved the issue.
