### ISSUE TITLE
view_metadata() help, more detail needed in value return

### ISSUE THREAD

**Issue by AmyHudson** [USDA-SCINet/rgeocdl#17]
is there any standardized metadata being returned?

**Comment by AmyHudson** [comment]
From view_metadata("MODIS_NDVI") 1) standardized metadata outputs are missing (e.g. Description: Provider name, Provider URL ) and 2) the product's temporal resolution should be included and isn't (didn't realize it was every 8 days). Because this is the only NDVI product right now, the user might not care, but especially if other products are added, the spatial grain and extent and temporal grain and extent are good metadata qualities to have for a user.

**Comment by HeatherSavoy-USDA** [comment]
makes sense! These changes will have to be made in GeoCDL itself so I'll make an issue over on that repo. I already made a similar one for #8 which is related to the every 8-day part.

**Comment by HeatherSavoy-USDA** [comment]
I've made the necessary changes in GeoCDL source code, but they won't be visible yet in `rgeocdl` until we refresh the service node. There is a placeholder for [temporal resolutions](https://github.com/USDA-SCINet/rgeocdl/issues/8) in `view_metadata()` for now that will populate with the resolutions once the GeoCDL service starts returning the info. I updated provider info for MODIS_NDVI and created a GeoCDL issue for the remaining datasets to be updated as well.

**Comment by HeatherSavoy-USDA** [comment]
Late update! 

Description, provider name, and provider url for each dataset in GeoCDL were added in https://github.com/stuckyb/gcdl/commit/9378c96c02bf460dd9b10637a74f43a8a2fa9af8. 

Temporal resolutions were added in https://github.com/stuckyb/gcdl/commit/4be011d1eeb2e5e7b18f4d2f9162be5c5a2d25b2.
