### ISSUE TITLE
Add 2023 annual cover and production to RAP dataset

### ISSUE THREAD

**Issue by gharrison159** [USDA-SCINet/rgeocdl#26]
The 2023 annual cover and production layers for the Rangeland Analysis Platform are now available, could these rasters please be added to the RAP folder in the GeoCDL? 
https://rangelands.app/products/#data-download

**Comment by HeatherSavoy-USDA** [comment]
The 2023 vegetation cover and biomass layers have been downloaded to Ceres, and the GeoCDL has been updated to accept requests for these layers.  

Note that dataset updates/additions are best suited for the main [GeoCDL repo](https://github.com/stuckyb/gcdl/issues), as opposed to this R interface repo.
