### ISSUE TITLE
help text needed for download_polygon_subset()

### ISSUE THREAD

**Issue by AmyHudson** [USDA-SCINet/rgeocdl#7]
Unclear what grain_method options there are in download_polygon_subset

"10.1.1.80:8000/subset_polygon?datasets=NASS_CDL%3Acdl%3BPRISM%3Appt&years=2000:2015&months=8&grain_method=finer&validate_method=strict&geom_guid=c38b2e0d-5c80-429f-96e5-5e3eb3f60d0d&resample_method=bilinear&resolution=1000"
Error in submit_subset_query(q_str, dsn) :
GeoCDL returned an error: Client error: (400) Bad Request NASS_CDL has no supported date granularity

**Comment by HeatherSavoy-USDA** [comment]
I updated the date related documentation with a 'Details' section. does that make things more clear?

**Comment by AmyHudson** [comment]
the grain method is clear now

**Comment by AmyHudson** [comment]
ri_method help in download_polygon_subset documentation needs to be changed form linear to bilinear (linear returns an error)

**Comment by HeatherSavoy-USDA** [comment]
Hmm I fixed that issue last week. Can you confirm you have the latest version installed?

**Comment by AmyHudson** [comment]
The path in the Session5_Tutorial1.Rmd workbook for is:
.libPaths(c(.libPaths(), '/project/geospatialworkshop/R_packages/4.2/'))

When I navigate to that folder says it was built 2022-08-30; and when I look at the rgeocdl package there it says version 0.1.0- is there a newer one than this:

Package: rgeocdl
Type: Package
Title: Accessing USDA-ARS SCINet GeoCDL with R
Version: 0.1.0
Author: Heather Savoy
Maintainer: Heather Savoy <heather.savoy@usda.gov>
Description: Provides user-friendly R functions to communicate with the 
  Geospatial Common Data Library (GeoCDL), a community effort by the USDA-ARS 
  SCINet Geospatial Working Group (https://www.scinet.usda.gov/).
License: GPL-3 + file LICENSE
Encoding: UTF-8
LazyData: true
Imports: httr, jsonlite, utils, dplyr, sf
RoxygenNote: 7.2.1
Suggests: knitr, rmarkdown
VignetteBuilder: knitr
Built: R 4.2.0; ; 2022-08-30 07:05:13 UTC; unix

**Comment by HeatherSavoy-USDA** [comment]
The latest version of rgeocdl is now the one accessible from this repo, e.g. via `install_github()`. The version in the shared project space is older and I haven't been updating it since this repo went public. 

(I also haven't done version numbers yet in the documentation, but will when we have some more issues resolved and we do an official release)

**Comment by AmyHudson** [comment]
Looks good!
