### ISSUE TITLE
add dimension information to view_metadata() output

### ISSUE THREAD

**Issue by AmyHudson** [USDA-SCINet/rgeocdl#8]
e.g. unclear in NASS Cropland Data Layer view_metadata("NASS_CDL") how many years are available- we have the upper and lower $date_ranges$year[[1]] as 2008 and [[2]] as 2021 but not sure how many years in that time frame.

**Comment by HeatherSavoy-USDA** [comment]
This is resolved, similar to #17, by  https://github.com/stuckyb/gcdl/commit/4be011d1eeb2e5e7b18f4d2f9162be5c5a2d25b2 and related commits.
